In [36]:
import numpy as np
from numpy import dtype

Numpy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations


In [37]:
from time import process_time

Time taken by a list

In [38]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [39]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0


Numpy Array

In [40]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [41]:
# creating a 1 dim array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [42]:
a.shape

(5,)

In [44]:
b = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)])
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [46]:
b.shape

(2, 5)

In [49]:
c = np.array([(1, 2, 3, 4), (5, 6, 7 , 8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays