In [36]:
import numpy as np
from numpy import dtype

Numpy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations


In [37]:
from time import process_time

Time taken by a list

In [38]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [39]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0


Numpy Array

In [40]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [41]:
# creating a 1 dim array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [42]:
a.shape

(5,)

In [44]:
b = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)])
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [46]:
b.shape

(2, 5)

In [49]:
c = np.array([(1, 2, 3, 4), (5, 6, 7 , 8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [54]:
# create a numpy array with zeroes

x = np.zeros((5, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
# create a numpy array with ones

y = np.ones((5, 4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [57]:
# array of a particular value

z = np.full((5, 4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [59]:
# create a identity matrix

a = np.eye(10)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [61]:
# create a numpy array with random numbers

b = np.random.random((5, 4))
print(b)

[[0.87223339 0.27799252 0.34354011 0.88694872]
 [0.86963798 0.23981527 0.80499137 0.4842957 ]
 [0.05482643 0.0528906  0.50663971 0.23049586]
 [0.43683743 0.14603625 0.23633242 0.65164639]
 [0.13113313 0.24450354 0.74719447 0.76223534]]


In [63]:
# random integer array with a specific range

c = np.random.randint(10,100, (5, 4))
print(c)

[[10 31 81 39]
 [77 98 54 80]
 [10 65 77 74]
 [81 89 50 56]
 [60 87 72 75]]


In [66]:
# array of evenly spaced values --> specifying the number of values replaced

d = np.linspace(10, 30, 5)
print(d)

[10. 15. 20. 25. 30.]


In [67]:
# array of evenly spaced values --> specifying the steps

e = np.arange(10, 30, 5)
print(e)

[10 15 20 25]


In [68]:
# convert a list to numpy array

list1 = [1, 2, 3, 4, 5]

np_array = np.asarray(list1)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Analysing a numpy array

In [70]:
c = np.random.randint(10,100, (5, 5))
print(c)

[[86 99 26 36 16]
 [22 84 65 89 75]
 [76 29 69 89 83]
 [61 87 29 80 67]
 [36 43 74 16 27]]


In [71]:
# array dimension

print(c.shape)

(5, 5)


In [72]:
# number of dimensions
print(c.ndim)

2


In [73]:
# number of elements
print(c.size)

25


In [74]:
# checking the data type of values in the array

print(c.dtype)

int32


Mathematical operations in a np array

In [76]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [79]:
a = np.random.randint(1, 10,(4, 5))
b = np.random.randint(10, 20,(4, 5))

In [80]:
print(a)
print(b)

[[4 5 5 5 5]
 [4 9 4 6 4]
 [8 7 3 1 1]
 [2 3 9 1 1]]
[[16 16 17 13 15]
 [18 17 19 17 14]
 [13 12 13 15 19]
 [12 17 18 17 16]]


In [81]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 21 22 18 20]
 [22 26 23 23 18]
 [21 19 16 16 20]
 [14 20 27 18 17]]
[[-12 -11 -12  -8 -10]
 [-14  -8 -15 -11 -10]
 [ -5  -5 -10 -14 -18]
 [-10 -14  -9 -16 -15]]
[[ 64  80  85  65  75]
 [ 72 153  76 102  56]
 [104  84  39  15  19]
 [ 24  51 162  17  16]]
[[0.25       0.3125     0.29411765 0.38461538 0.33333333]
 [0.22222222 0.52941176 0.21052632 0.35294118 0.28571429]
 [0.61538462 0.58333333 0.23076923 0.06666667 0.05263158]
 [0.16666667 0.17647059 0.5        0.05882353 0.0625    ]]


In [82]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20 21 22 18 20]
 [22 26 23 23 18]
 [21 19 16 16 20]
 [14 20 27 18 17]]
[[-12 -11 -12  -8 -10]
 [-14  -8 -15 -11 -10]
 [ -5  -5 -10 -14 -18]
 [-10 -14  -9 -16 -15]]
[[ 64  80  85  65  75]
 [ 72 153  76 102  56]
 [104  84  39  15  19]
 [ 24  51 162  17  16]]
[[0.25       0.3125     0.29411765 0.38461538 0.33333333]
 [0.22222222 0.52941176 0.21052632 0.35294118 0.28571429]
 [0.61538462 0.58333333 0.23076923 0.06666667 0.05263158]
 [0.16666667 0.17647059 0.5        0.05882353 0.0625    ]]


In [85]:
array = np.random.randint(0, 10, (2, 3))
print(array)
array.shape

[[3 8 5]
 [2 3 0]]


(2, 3)

In [86]:
trans = np.transpose(array)
print(trans)
trans.shape

[[3 2]
 [8 3]
 [5 0]]


(3, 2)

In [87]:
array = np.random.randint(0, 10, (2, 3))
print(array)
array.shape

[[1 7 1]
 [2 9 2]]


(2, 3)

In [88]:
trans2 = array.T
print(trans2)
trans2.shape

[[1 2]
 [7 9]
 [1 2]]


(3, 2)